### ISSUE TITLE
Complete basic attributes to enable a sensible JSDoc generation

### ISSUE THREAD

**Issue by maxbartunik** [PagerBuddy/Server#10]
We have a draft of generated JSDoc: https://pagerbuddy.github.io/Server/

Obviously our markup still needs some work...

**Comment by keszocze** [comment]
What exactly do you refer to? I mean, to me it looks as if the JSDoc simply isn't fully done in the source code. The pages themselves look correct to (just not very helpful).

**Comment by maxbartunik** [comment]
That is what I mean - add JSDoc annotations for modules etc...
