### ISSUE TITLE
Should we have a separate DB for testing purposes?

### ISSUE THREAD

**Issue by keszocze** [PagerBuddy/Server#21]
I think that it would be nice to have a database pre-filled with test data so that we can easily run tests without having to setup everything in the test cases over and over again. 

We could realize that with a `.sql` file that only creates the DB when tests are run. This would prevent creating the DB unnecessarily (i.e. when an end-user runs PagerBuddy).

@maxbartunik what is your opinion on that?

**Comment by maxbartunik** [comment]
Happy about that :)

**Comment by keszocze** [comment]
I solved the problem by creating an in-memory DB before the test cases run. This is rather nice as we do not have to check for any files being at the right position.
