### ISSUE TITLE
Test health

### ISSUE THREAD

**Issue by keszocze** [PagerBuddy/Server#23]
Status at the moment of issue creation:

File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                        
------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------------------                        
  health.mjs            |   53.84 |    25.75 |      70 |   53.84 | 65-75,94,173-225

**Comment by maxbartunik** [comment]
Closing as obsolete
