### ISSUE TITLE
Test messaging

### ISSUE THREAD

**Issue by keszocze** [PagerBuddy/Server#24]
Status at issue creation:
File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                        
------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------------------                                                                                                        
  messaging.mjs         |    7.44 |        0 |    7.14 |    7.44 | 48-310

**Comment by maxbartunik** [comment]
Closing as obsolete
