### ISSUE TITLE
Test websocket

### ISSUE THREAD

**Issue by keszocze** [PagerBuddy/Server#25]
Status at issue creation:

File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                        
------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------------------                                                                                                                                                                                                 
websocket.mjs         |   17.07 |       25 |   15.38 |   17.07 | 42-94,101,105

**Comment by maxbartunik** [comment]
Closing as obsolete
