### ISSUE TITLE
Test telegram/bot

### ISSUE THREAD

**Issue by keszocze** [PagerBuddy/Server#26]
Status at issue creation:

File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                        
------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------------------                                                                                                     
  bot.mjs               |    3.87 |        0 |    2.77 |    3.96 | 78-995

**Comment by maxbartunik** [comment]
Closing as obsolete
