### ISSUE TITLE
Test telegram/queue

### ISSUE THREAD

**Issue by keszocze** [PagerBuddy/Server#27]
Status at issue creation:

File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                        
------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------------------                                                                                                         
  queue.js              |    7.01 |        0 |    7.14 |    7.01 | 50-199

**Comment by maxbartunik** [comment]
Closing as obsolete
