### ISSUE TITLE
Test telegram/response-overview

### ISSUE THREAD

**Issue by keszocze** [PagerBuddy/Server#28]
Status at issue creation:

File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                        
------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------------------                                                                                               
  response-overview.js  |   11.36 |        0 |    8.33 |   11.36 | 111-415

**Comment by maxbartunik** [comment]
Closing as obsolete
