### ISSUE TITLE
Model domain using classes

### ISSUE THREAD

**Issue by keszocze** [PagerBuddy/Server#3]
I wanted to start implementing the DB connection as a class in order to make the intended transition to using an ORM smoother. I copied the way to initialize the db from the `data.mjs` file into the `db.mjs` file in the `dbclass` branch.

To achieve high code quality, I immediately started adding jest test. But already the first one failed. I wanted to make sure that the initialization is safe, i.e. an exception is thrown when no connection to the DB can be made. But only one of the three tests work as expected. 

@maxbartunik you already worked with the sqlite library. Is this an issue due to some stupid aysnc happening in the background?

**Comment by keszocze** [comment]
Fancy, now this is priority number one :)

**Comment by maxbartunik** [comment]
Does this issue imply the introduction of DB middleware or should we add a seperate (priority) issue for that?

**Comment by keszocze** [comment]
Yes, it should be a separate issue. I will rename this issue to better capture what actually is done.

**Comment by keszocze** [comment]
This has actually been implemented. For some reason, we forgot to automatically close this when the corresponding pull request was merged.
