### ISSUE TITLE
Versioning/Release Plan

### ISSUE THREAD

**Issue by keszocze** [PagerBuddy/Server#32]
We should discuss and decide on
1) how to version and
2) when to release

### Ad 1
I believe that we should use [semantic versioning](https://semver.org/) (without buying too much into this MUST/SHALL bla bla wording). We should keep a changelog. Looking at the difference between `main` and `development`, I would add the following `changelog.md`:
```
# Version 1.0. (TBA)

## Added

## Fixed
* Issues with systemd when installing PagerBuddy Server on Linux systems

## Removed

# Version 1.0 (2022-08-13)

Initial Version
```

### Ad 2
I think we should adopt a ["release early, release often"](https://en.wikipedia.org/wiki/Release_early,_release_often) scheme. This will allow us to get early feedback from users. Also it creates the illusion of us working on PagerBuddy at an incredible pace.

I would create projects collecting some issues to releases smaller than V2, if my proposal here is accepted.

@kats-reichert @maxbartunik I'd like to hear your opinion on this.

**Comment by maxbartunik** [comment]
Ad 1 - definately
Ad 2 - Principally yes. However, 
a) we have to ensure that a release is always bug-free in regard to alert functionality (receiving & sending alerts) as every missed/wrong alert has a potentially fatal impact, 
b) our current issues on v1 are nearly exclusively regarding code quality and not functionality. These issues do not have a large/any impact on the end user but take up a lot of time changing code that will be obsolete/need rework for v2. I therefore would aim at freezing "code quality" work ASAP, completing WIP and then focus on the changes needed for v2.

**Comment by maxbartunik** [comment]
Perhaps we should reduce the v2 hurdle by initially eliminating the UI upgrade (v2.0.0) and adding it later (v2.1.0).

**Comment by keszocze** [comment]
> Perhaps we should reduce the v2 hurdle by initially eliminating the UI upgrade (v2.0.0) and adding it later (v2.1.0).

Absolutely fine with me. But this is already a discussion on the concrete realization. I wanted to get feedback on the general idea (where we seem to agree on).

>  we have to ensure that a release is always bug-free [...]

Absolutely! I never intended to suggest otherwise.

> our current issues on v1 are nearly exclusively regarding code quality [...] I therefore would aim at freezing "code quality" work ASAP, completing WIP and then focus on the changes needed for v2.

OK, what exactly do you propose? I want #20 (mainly meaning #3) to be finally finished as this will actually/hopefully help us moving towards a better DB altogether.

I think these details should be discusses elsewhere as this was more to ask for general consensus. Please note pull request #33
