### ISSUE TITLE
Use better class for Date/Time

### ISSUE THREAD

**Issue by keszocze** [PagerBuddy/Server#36]
Working with date and time in JavaScript is a pain. We should try to find a more suitable package for working with dates. [date-fns](https://date-fns.org/docs/Getting-Started) seems to be used quite often. [This page](https://www.skypack.dev/blog/2021/02/the-best-javascript-date-libraries/) discusses some date libraries.

From my current perspective, I vote for `date-fns`.

**Comment by maxbartunik** [comment]
I am not fully happy with how date-fns handles timezones, but from what I see it seems to be the best solution. We will just have to (continue to) be careful about using UTC internally (i.e. .zonedTimetoUTC() and similar).

**Comment by keszocze** [comment]
I do not have any preferences. What about [luxon](https://moment.github.io/luxon/#/tour)?

**Comment by maxbartunik** [comment]
I tried date-fns and found it very clumsy with times. O have decided to try with luxor: https://github.com/PagerBuddy/Server/pull/70
