### ISSUE TITLE
Bot parsing "cleanup"

### ISSUE THREAD

**Issue by keszocze** [PagerBuddy/Server#4]
I'd like to implement the following suggestions made in PagerBuddy/ArchivedServer#86

* Remove the [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)#Unnamed_numerical_constants) in the following code
```javascript
 let out_zvei = zvei_id;
  if(config["CONFIDENTIAL_MODE"]){
    text = "Alert anonymised";
    out_zvei = 10000;
```
But for that I need to know what the `10000` stands for.
* Remove some unused variables
* Remove
```javascript
bot.onText(/.+/, async function (msg, match) {});
```
entirely as, if I understand it correctly, adds a "do nothing" function for the case that the bot is not supposed to do anything. I believe that it is more intuitive if we simply do not define a `onText` function at all. But I have to check that this will not break the bot.
* I'd like to replace the "magic lines" `case (new RegExp(`^\\/zveiList(?:@${BOT_NAME})?`)).test(msg.text):` by
 ```javascript
const zveiListReg= new RegExp(`^\\/zveiList(?:@${BOT_NAME})?`)
// ...
case (zweiListReg.test(msg.text)): // ...
```
* The following looks like doing things over and over:
```javascript
            case (new RegExp(`^\\/addZVEI(?:@${BOT_NAME})?\\s[0-9]{1,5}\\s([\\wäÄöÖüÜß()\\-\\s]+)`)).test(msg.text):
                let zvei_description = msg.text.match(new RegExp(`\\/addZVEI(?:@${BOT_NAME})?\\s[0-9]{1,5}\\s([\\wäÄöÖüÜß()\\-\\s]+)`))[1];
                let zvei_id = parseInt(msg.text.match(new RegExp(`\\/addZVEI(?:@${BOT_NAME})?\\s([0-9]{1,5})\\s`))[1]);
```
Did you implement it that way because the match object is no accessible within the case block? My proposal is to do something like this:
```javascript
// note the two capture groups of the regex!
const addZVEIReg = new RegExp(`\\/addZVEI(?:@${BOT_NAME})?\\s([0-9]{1,5})\\s([\\wäÄöÖüÜß()\\-\\s]+)`)
const matchedAddZVEI = msg.text.match(adZVEIReg)
// ...
case matchedAddZVEI: // if the regex did not match it is `null` and the case should not match
   let zvei_description = matchedAddZVEI[2];
   let zvei_id = parseInt(matchedAddZVEI[1]);
   // ....
```

Before starting on this, I'd like to know @maxbartunik 's opinion on this.

**Comment by maxbartunik** [comment]
This has become obsolete with v2.
