### ISSUE TITLE
Fix Telegram transport

### ISSUE THREAD

**Issue by maxbartunik** [PagerBuddy/Server#50]
Currently the watson transport for Telegram is not reporting correctly (e.g. from Server or Health). We had similar issues before - this is probably due to the order of import statements.

**Comment by keszocze** [comment]
Do we have a corresponding test case?

**Comment by maxbartunik** [comment]
Good point - I believe not.

**Comment by maxbartunik** [comment]
This is actually not reporting at all - it appears to be a problem with the binding of the method. The call here (confirmed for a non-NULL zvei (e.g. zvei = 3)
https://github.com/PagerBuddy/Server/blob/154e2aa87fbd3546963942db40d7800b9d684ba4/src/telegramTransport.mjs#L58
results in a query
```
SELECT Groups.chat_id
FROM Alarms
JOIN Groups ON Alarms.group_id = Groups.group_id
JOIN ZVEI ON Alarms.zvei_id = ZVEI.zvei_id
WHERE ZVEI.zvei_id = NULL
```
