### ISSUE TITLE
Handle whitespace padding in KatSys

### ISSUE THREAD

**Issue by maxbartunik** [PagerBuddy/Server#62]
Real life KatSys alerts often have whitespace padding before/after the "schleifen" segment - as we currently ensure we only have exactly 3 parameters (once split by whitespace) this causes errors. We should strip a schleifen segment of leading and tailing whitespace before attempting to extract information.

Error sample (anonymised):
"schleifen_delta":"456 25123 16:00\n 456 25124 16:00\nRD_ER 5123 16:00"
```
[KatSys] warn: Error generating alert list: Error: Too many parameters for Schleife provided:  456 25124 16:00
```

Relavant code:
https://github.com/PagerBuddy/Server/blob/154e2aa87fbd3546963942db40d7800b9d684ba4/src/katsys/schleife.mjs#L15-L17

**Comment by keszocze** [comment]
Is the problem the whitespace highlighted as follows?
```json
"schleifen_delta":"456 25123 16:00\n␣456 25124 16:00\nRD_ER 5123 16:00"
```

**Comment by maxbartunik** [comment]
correct

**Comment by maxbartunik** [comment]
I think it would be sensible to blindly remove any leading/trailing whitespace from schleife_desc in the code section above
