### ISSUE TITLE
Provide feedback to user if arguments are not 'safe'

### ISSUE THREAD

**Issue by Benjamin-Schiller** [PagerBuddy/Server#8]
So far, whenever an argument is not safe (is_chat_id_safe(...) == False), the function just returns without feedback.

-> Provide feedback to user

**Comment by keszocze** [comment]
Can you point me to some instances of this problem? I'd like to tackle this.

**Comment by Benjamin-Schiller** [comment]
This referred to functions like this:

https://github.com/PagerBuddy/Server/blob/acde9c1fe600db0a91e67115883d9a5fb2eae7b3/src/data.js#L130

But it looks like someone already implemented feedback there, so maybe this issue has already been addressed, but not closed.

**Comment by maxbartunik** [comment]
This originally referred to admin actions through the Telegram config (e.g. any Telegram command). I feel this is not an essential or even very valuable feature extension for the current v1. This will be obsolete with v2.
I would therefore close this issue as not to be implemented.
